adding little bit test for the vilidate the file is tsv style or not

diff --git a/cantril_data_cleaning b/cantril_data_cleaning
--- a/cantril_data_cleaning
+++ b/cantril_data_cleaning
@@ -2,24 +2,26 @@
 # CITS 4407 Assignment 2
 # Author Zishan Luo
 # Student ID 22448064
-#!/bin/bash
-
+invalid_format=false
 # Function to check if a file is tab-separated, read the tsv header.
 # Check if the input is three file or not.
-function check_tab_separated() {
-    if [ $# -ne 3 ]; then
-        echo "Error: Expected 3 input files, received $#"
-        exit 1
-    fi
 
-    for file in "$@"; do
-      # using head command -n 1 => read the first line(title of tsv) and check is
-      # a file if
-        header=$(head -n 1 "$file")
-        if [[ $header != *$'\t'* ]]; then
-            echo "Invalid file format in $file. File is not tab-separated."
-            exit 1
-        fi
-    done
-}
-check_tab_separated "$1" "$2" "$3"
+if [ $# -ne 3 ]; then
+    echo "Error: Expected 3 input files, received $#"
+    exit 1
+fi
+
+for file in "$@"; do
+    # using head command -n 1 => read the first line(title of tsv) and check is
+    # a file if
+    header=$(head -n 1 "$file")
+    if [[ $header != *$'\t'* ]]; then
+        echo "Invalid file format in $file. File is not tab-separated."
+#        exit 1
+        invalid_format=true
+    fi
+done
+
+if [ "$invalid_format" = false ]; then
+    echo "Thanks"
+fi
